# Generated by Django 2.1.8 on 2019-08-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_saleinvoiceitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoiceitem',
            name='user',
        ),
        migrations.AddField(
            model_name='saleinvoiceitemhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_user_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
