# Generated by Django 2.1.8 on 2019-08-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190827_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.FloatField(default=0.0)),
                ('remain', models.FloatField(default=0.0)),
                ('pay_status', models.CharField(choices=[('FULL', 'Full'), ('OWE', 'Owe')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pay_date', models.DateTimeField(blank=True)),
                ('is_status', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoice', to='customer.SaleInvoice')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
