# Generated by Django 2.1.8 on 2019-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(choices=[('NO', 'No'), ('FULL', 'Full'), ('OWE', 'Owe')], max_length=10),
        ),
    ]
