# Generated by Django 2.1.8 on 2019-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190827_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(choices=[('', ''), ('FULL', 'Full'), ('OWE', 'Owe')], max_length=10),
        ),
    ]
