# Generated by Django 2.1.8 on 2019-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_payment_receive_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
