# Generated by Django 2.1.8 on 2019-09-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_saleinvoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='file',
        ),
    ]
