# Generated by Django 2.1.8 on 2019-12-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20191128_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='discount_unit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
