# Generated by Django 2.1.8 on 2019-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_saleinvoiceitem_discount_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='saleinvoiceitem',
            name='discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='saleinvoiceitem',
            name='discount_unit',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
