# Generated by Django 2.1.8 on 2019-08-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='special_pprice',
            new_name='special_price',
        ),
    ]
