# Generated by Django 2.1.8 on 2019-08-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190810_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date_discount',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date_discount',
            field=models.DateTimeField(),
        ),
    ]
