# Generated by Django 2.1.8 on 2019-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190810_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
