# Generated by Django 2.1.8 on 2019-08-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productcategory_is_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='rice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='producthistory',
            old_name='special_pprice',
            new_name='special_price',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='action',
            field=models.CharField(default='', max_length=10),
        ),
    ]
