# Generated by Django 2.1.8 on 2019-08-11 07:53

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190811_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='end_date_discount',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='start_date_discount',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_image',
            field=models.FileField(blank=True, upload_to=product.models.user_directory_path, validators=[product.models.validate_file_extension]),
        ),
    ]
