# Generated by Django 2.1.8 on 2019-08-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productinstockhistory_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productinstock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productinstockhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subproductimage',
            options={'ordering': ['-created_at']},
        ),
    ]
