# Generated by Django 2.1.8 on 2019-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190817_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='email',
            field=models.EmailField(default='kimlongngin@gmail.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='phone_number',
            field=models.CharField(default='012323288', max_length=150),
            preserve_default=False,
        ),
    ]
