# Generated by Django 2.1.8 on 2019-08-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190817_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstock',
            name='stock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.StockLocation'),
        ),
    ]
