# Generated by Django 2.1.8 on 2019-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='productinstock',
            name='unit_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
