# Generated by Django 2.1.8 on 2019-08-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190817_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstock',
            name='unit_title',
        ),
        migrations.RemoveField(
            model_name='productinstockhistory',
            name='unit_title',
        ),
    ]
