# Generated by Django 2.1.8 on 2019-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190817_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
