# Generated by Django 2.1.8 on 2019-08-22 11:50

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20190817_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='default_image',
            field=models.FileField(blank=True, upload_to=product.models.user_directory_path, validators=[product.models.validate_file_extension]),
        ),
    ]
