# Generated by Django 2.1.8 on 2019-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productcategory_default_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='default_image',
            new_name='icon',
        ),
    ]
