# Generated by Django 2.1.8 on 2019-09-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productinstock_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstock',
            name='controller',
        ),
    ]
