# Generated by Django 2.1.8 on 2019-09-10 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_productinstock_stock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_stock', to='product.Product'),
        ),
    ]
