# Generated by Django 2.1.8 on 2019-11-27 02:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.FileField(upload_to=product.models.user_directory_path, validators=[product.models.validate_file_extension]),
        ),
    ]
