# Generated by Django 2.1.8 on 2019-08-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0003_auto_20190821_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontrol',
            old_name='name',
            new_name='user',
        ),
    ]
