# Generated by Django 2.1.8 on 2019-08-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0004_auto_20190821_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontrol',
            name='name',
            field=models.CharField(default='kimlong', max_length=50),
            preserve_default=False,
        ),
    ]
